/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PartialHashGlobOptions {
  cwd?: string
  gitignore?: boolean
}
export function hashGlob(globs: Array<string>, maybeOptions?: PartialHashGlobOptions | undefined | null): Array<bigint> | null
